import { Metadata } from 'next'

const defaultMetadata: Metadata = {
  metadataBase: new URL('https://blood-donor-rangpur.vercel.app'),
  title: {
    default: 'LifeDrop | বাংলাদেশের সকল বিভাগের রক্তদান কমিউনিটিতে যোগ দিন। রক্তদাতা খুঁজুন, রক্তদান করুন, জীবন বাঁচান।',
    template: '%s | LifeDrop'
  },
  description: 'বাংলাদেশের সকল বিভাগের রক্তদান কমিউনিটিতে যোগ দিন। রক্তদাতা খুঁজুন, রক্তদান করুন, জীবন বাঁচান।',
  keywords: [
    'রক্তদান',
    'বাংলাদেশ',
    'ঢাকা',
    'চট্টগ্রাম',
    'রাজশাহী',
    'খুলনা',
    'বরিশাল',
    'সিলেট',
    'রংপুর',
    'ময়মনসিংহ',
    'ব্লাড ডোনেশন',
    'রক্তদাতা',
    'রক্তদান সেবা',
    'blood donation',
    'bangladesh',
    'dhaka',
    'chittagong',
    'rajshahi',
    'khulna',
    'barisal',
    'sylhet',
    'rangpur',
    'mymensingh',
    'blood donor',
    'blood bank',
    'blood donation app',
    'blood donation website',
    'blood donation platform',
    'blood donation community',
    'blood donation network',
    'blood donation service',
    'blood donation organization',
    'blood donation campaign',
    'blood donation drive',
    'blood donation center',
    'blood donation clinic',
    'blood donation hospital',
    'blood donation emergency',
    'blood donation volunteer',
    'blood donation registration',
    'blood donation schedule',
    'blood donation appointment',
    'blood donation eligibility',
    'blood donation requirements',
    'blood donation benefits',
    'blood donation process',
    'blood donation safety',
    'blood donation awareness',
    'blood donation education',
    'blood donation information',
    'blood donation statistics',
    'blood donation facts',
    'blood donation tips',
    'blood donation guidelines',
    'blood donation procedure',
    'blood donation types',
    'blood donation groups',
    'blood donation compatibility',
    'blood donation matching',
    'blood donation request',
    'blood donation need',
    'blood donation shortage',
    'blood donation supply',
    'blood donation demand',
    'blood donation crisis',
    'blood donation emergency',
    'blood donation lifesaving',
    'blood donation charity',
    'blood donation nonprofit',
    'blood donation humanitarian',
    'blood donation social service',
    'blood donation community service',
    'blood donation public health',
    'blood donation healthcare',
    'blood donation medical',
    'blood donation transfusion',
    'blood donation plasma',
    'blood donation platelets',
    'blood donation red cells',
    'blood donation whole blood',
    'blood donation A positive',
    'blood donation A negative',
    'blood donation B positive',
    'blood donation B negative',
    'blood donation AB positive',
    'blood donation AB negative',
    'blood donation O positive',
    'blood donation O negative',
    'blood donation universal donor',
    'blood donation universal recipient',
    'blood donation rare blood type',
    'blood donation common blood type',
    'blood donation mobile app',
    'blood donation online platform',
    'blood donation digital service',
    'blood donation technology',
    'blood donation innovation',
    'blood donation solution',
    'blood donation finder',
    'blood donation locator',
    'blood donation tracker',
    'blood donation management',
    'blood donation system',
    // Districts in Bangla
    'কুমিল্লা',
    'ফেনী',
    'ব্রাহ্মণবাড়িয়া',
    'রাঙ্গামাটি',
    'নোয়াখালী',
    'চাঁদপুর',
    'লক্ষ্মীপুর',
    'চট্টগ্রাম',
    'কক্সবাজার',
    'খাগড়াছড়ি',
    'বান্দরবান',
    'সিরাজগঞ্জ',
    'পাবনা',
    'বগুড়া',
    'রাজশাহী',
    'নাটোর',
    'জয়পুরহাট',
    'চাঁপাইনবাবগঞ্জ',
    'নওগাঁ',
    'যশোর',
    'সাতক্ষীরা',
    'মেহেরপুর',
    'নড়াইল',
    'চুয়াডাঙ্গা',
    'কুষ্টিয়া',
    'মাগুরা',
    'খুলনা',
    'বাগেরহাট',
    'ঝিনাইদহ',
    'ঝালকাঠি',
    'পটুয়াখালী',
    'পিরোজপুর',
    'বরিশাল',
    'ভোলা',
    'বরগুনা',
    'সিলেট',
    'মৌলভীবাজার',
    'হবিগঞ্জ',
    'সুনামগঞ্জ',
    'নরসিংদী',
    'গাজীপুর',
    'শরীয়তপুর',
    'নারায়ণগঞ্জ',
    'টাঙ্গাইল',
    'কিশোরগঞ্জ',
    'মানিকগঞ্জ',
    'ঢাকা',
    'মুন্সিগঞ্জ',
    'রাজবাড়ী',
    'মাদারীপুর',
    'গোপালগঞ্জ',
    'ফরিদপুর',
    'পঞ্চগড়',
    'ঠাকুরগাঁও',
    'দিনাজপুর',
    'রংপুর',
    'কুড়িগ্রাম',
    'গাইবান্ধা',
    'লালমনিরহাট',
    'নীলফামারী',
    'জামালপুর',
    'শেরপুর',
    'ময়মনসিংহ',
    'নেত্রকোণা',
    // Districts in English
    'Comilla',
    'Feni',
    'Brahmanbaria',
    'Rangamati',
    'Noakhali',
    'Chandpur',
    'Lakshmipur',
    'Chattogram',
    'Cox\'s Bazar',
    'Khagrachhari',
    'Bandarban',
    'Sirajganj',
    'Pabna',
    'Bogura',
    'Rajshahi',
    'Natore',
    'Joypurhat',
    'Chapainawabganj',
    'Naogaon',
    'Jashore',
    'Satkhira',
    'Meherpur',
    'Narail',
    'Chuadanga',
    'Kushtia',
    'Magura',
    'Khulna',
    'Bagerhat',
    'Jhenaidah',
    'Jhalokati',
    'Patuakhali',
    'Pirojpur',
    'Barishal',
    'Bhola',
    'Barguna',
    'Sylhet',
    'Moulvibazar',
    'Habiganj',
    'Sunamganj',
    'Narsingdi',
    'Gazipur',
    'Shariatpur',
    'Narayanganj',
    'Tangail',
    'Kishoreganj',
    'Manikganj',
    'Dhaka',
    'Munshiganj',
    'Rajbari',
    'Madaripur',
    'Gopalganj',
    'Faridpur',
    'Panchagarh',
    'Thakurgaon',
    'Dinajpur',
    'Rangpur',
    'Kurigram',
    'Gaibandha',
    'Lalmonirhat',
    'Nilphamari',
    'Jamalpur',
    'Sherpur',
    'Mymensingh',
    'Netrokona'
  ],
  authors: [{ name: 'Tajbir Islam' }],
  creator: 'Tajbir Islam',
  publisher: 'LifeDrop',
  formatDetection: {
    email: true,
    address: true,
    telephone: true,
  },
  openGraph: {
    type: 'website',
    locale: 'bn_BD',
    siteName: 'LifeDrop',
    images: [
      {
        url: '/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'LifeDrop',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'LifeDrop',
    description: 'বাংলাদেশের সকল বিভাগের রক্তদান কমিউনিটিতে যোগ দিন। রক্তদাতা খুঁজুন, রক্তদান করুন, জীবন বাঁচান।',
    images: ['/og-image.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: '4r6L_E636xBF3hU6OjXMUdfSnfTKiwofEtBSHhxMHRw',
  },
  alternates: {
    canonical: 'https://blood-donor-rangpur.vercel.app',
  },
  manifest: '/manifest.json',
}

export function generateMetadata({
  title,
  description,
  path,
  noIndex = false,
}: {
  title: string
  description: string
  path: string
  noIndex?: boolean
}): Metadata {
  const url = `https://blood-donor-rangpur.vercel.app${path}`
  
  return {
    ...defaultMetadata,
    title,
    description,
    robots: noIndex ? { index: false, follow: false } : defaultMetadata.robots,
    openGraph: {
      ...defaultMetadata.openGraph,
      title,
      description,
      url,
    },
    twitter: {
      ...defaultMetadata.twitter,
      title,
      description,
    },
    alternates: {
      canonical: url,
    },
  }
}

export { defaultMetadata } 